### ISSUE TITLE
weight

### ISSUE THREAD

**Issue by weiling666** [yifanzhang-pro/RelationMatch#1]
Can you share the weight setting of relation-loss,THAHKS YOU

**Comment by yifanzhang-pro** [comment]
Thanks for your attention, according to Equation (4) in https://arxiv.org/pdf/2305.10397.pdf, we simply set the $\mu_u$ as 0.003, and the ratio between CE and MCE to be 1. You can try some ablation studies on these hyperparameters, especially on different datasets settings.

**Comment by weiling666** [comment]
Thank you for your research and your response
